package Services.MDPatternDetection.AnnotationClasses;

public enum Annotations {
    FACT, DIMENSION, DIMENSIONLEVEL, PARENTLEVEL, DIMENSIONATTRIBUTE, FACTATTRIBUTE, NONFUNCTIONALDIMENSION, NONFUNCTIONALDIMENSIONLEVEL, MEASURE
}
